version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - memcached

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3308:3306"
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  memcached:
    image: memcached:latest
    ports:
      - "11220:11211"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8040:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
